# Generated by Django 3.0 on 2021-07-26 14:16

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название направления', max_length=100, verbose_name='Название направления')),
                ('name_English', models.CharField(help_text='Название направления на английском языке', max_length=100, unique=True, verbose_name='Название направления  на английском языке')),
            ],
            options={
                'verbose_name': 'Направление',
                'verbose_name_plural': 'Направления',
            },
        ),
        migrations.CreateModel(
            name='LendingHome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='имя', max_length=50, verbose_name='имя')),
                ('phone', models.CharField(help_text='телефон', max_length=12, verbose_name='телефон')),
                ('email', models.EmailField(help_text='email', max_length=254, verbose_name='email')),
                ('date', models.DateTimeField(auto_now=True, help_text='дата', verbose_name='дата')),
            ],
            options={
                'verbose_name': 'Лендинг',
                'verbose_name_plural': 'Лендинг',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='Гость', max_length=50, verbose_name='Имя')),
                ('second_name', models.CharField(blank=True, max_length=150, verbose_name='Фамилия')),
                ('photo', models.ImageField(blank=True, upload_to='Reviews/%Y.%M.%D')),
                ('review', models.TextField(verbose_name='Отзыв')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('profession', models.CharField(max_length=300, verbose_name='Профессия')),
                ('photo', models.ImageField(help_text='Желательно загружать изображения в соотношении 1:1', upload_to='teachers', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
        migrations.CreateModel(
            name='Webinar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('datetime', models.DateTimeField(verbose_name='Дата и время')),
                ('link', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ссылка')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('files', models.CharField(blank=True, help_text='Ссылка на облачное хранилище с файлами для вебинара', max_length=500, null=True, verbose_name='Ссылка на файлы')),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', max_length=18, verbose_name='Фон')),
                ('color_2', colorfield.fields.ColorField(default='#FFFFFF', max_length=18, verbose_name='Цвет текста')),
                ('photo_preview', models.ImageField(upload_to='webinars_photo_preview', verbose_name='Фото preview')),
                ('recommend', models.BooleanField(default=False, verbose_name='Рекомендовано?')),
                ('published', models.BooleanField(default=False, verbose_name='Доступно пользователям?')),
                ('kol_prosm', models.BigIntegerField(default=0, verbose_name='Количество просмотров')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.Direction', verbose_name='Направление')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.Teacher', verbose_name='Учитель')),
            ],
            options={
                'verbose_name': 'Вебинар',
                'verbose_name_plural': 'Вебинары',
                'ordering': ['-datetime'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название курса', max_length=100, verbose_name='Название курса')),
                ('name_2', models.CharField(blank=True, help_text='Вторая строка названия курса', max_length=100, null=True, verbose_name='Название курса вторая строка')),
                ('image_course', models.ImageField(help_text='Выбери картинку для курса', upload_to='courses_images', verbose_name='Картинка для курса')),
                ('how_long', models.CharField(help_text='Введи длительность курса. Например: 3 месяца', max_length=50, verbose_name='Длительность курса')),
                ('min_price', models.BigIntegerField(default=1990, help_text='Введи минимкльную цену. Например: 1990', verbose_name='Минимальная цена')),
                ('standart_price', models.BigIntegerField(default=4990, help_text='Введи цену стандартного курса. Например: 4990', verbose_name='Стандартная цена')),
                ('vip_price', models.BigIntegerField(default=9490, help_text='Введи  VIP цену. Например: 9490', verbose_name='VIP цена')),
                ('type_study', models.CharField(choices=[('Profession', 'Profession'), ('Profession', 'Course')], max_length=50, verbose_name='Тип обучения')),
                ('lvl_hard', models.CharField(choices=[('Easy', 'Easy'), ('Hard', 'Hard')], max_length=50, verbose_name='Уровень сложности')),
                ('background_color', colorfield.fields.ColorField(default='#fff', help_text='Введи цвет фона курса. Например: #b4e682', max_length=7, verbose_name='Фоновый Цвет курса')),
                ('color_2', colorfield.fields.ColorField(default='#fff', help_text='второй цвет', max_length=7, verbose_name='второй Цвет курса')),
                ('search_keys', models.TextField(verbose_name='Ключи для поиска')),
                ('recommend', models.BooleanField(default=False, verbose_name='Рекомендовано?')),
                ('direction', models.ForeignKey(help_text='Выбери направление', on_delete=django.db.models.deletion.PROTECT, to='home.Direction', verbose_name='Направление')),
                ('teachers', models.ManyToManyField(related_name='courses', to='home.Teacher')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
    ]
