# Generated by Django 3.0 on 2021-09-19 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_lendinghome'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LendingHome',
        ),
    ]
